version: '2'
services:
  mysql:
    container_name: mysql-dev
    ports:
      - "6612:3306"
    restart: always
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=blockchain-trade-game
